local telescope = require("telescope")
local builtin = require("telescope.builtin")

vim.keymap.set("n", "<leader>F", builtin.find_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>rf", telescope.extensions.recent_files.recent_files, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>ff", telescope.extensions.recent_files.pick, { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fg", telescope.extensions.egrepify.egrepify, { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>mm", telescope.extensions.messages.messages, { desc = "Telescope messages" })

vim.keymap.set("n", "<leader>fw", function()
	local word = vim.fn.expand("<cword>")
	require("telescope.builtin").live_grep({ default_text = word })
end)
vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Telescope buffers" })
print(vim.inspect(require("telescope").extensions))
