local ls = require("luasnip")
local s = ls.snippet
local i = ls.insert_node
local fmt = require("luasnip.extras.fmt").fmt

return {

  s("radioprimary", fmt([[
@components.PrimaryRadio(&structs.Radio{{
	ID: {},
	Name: {},
	Value: {},
	Disabled: {},
	Method: {},
	URL: {},
	Target: {},
	Include: {},
	Trigger: {},
	Swap: {},
	Indicator: {},
	Vals: {},
	Confirm: {},
	PushURL: {},
	Boost: {},
	Constraint: {},
	DirtyWatch: {},
	DirtyGroup: {},
	EnableOnValid: {},
	EnableTarget: {},
	ConstraintForm: {},
	Checked: {},
	Required: {},
}})
  ]], {
    i(1, ""),
    i(2, ""),
    i(3, "Click Me"),
    i(4, "false"),
    i(5, "structs.POST"),
    i(6, "/endpoint"),
    i(7, ""),
    i(8, ""),
    i(9, ""),
    i(10, "innerHTML"),
    i(11, ""),
    i(12, ""),
    i(13, ""),
    i(14, ""),
    i(15, "false"),
    i(16, ""),
    i(17, "false"),
    i(18, ""),
    i(19, "false"),
    i(20, ""),
    i(21, "false"),
    i(22, "false"),
    i(23, "false"),
  })),


  s("radiosecondary", fmt([[
@components.SecondaryRadio(&structs.Radio{{
	ID: {},
	Name: {},
	Value: {},
	Disabled: {},
	Method: {},
	URL: {},
	Target: {},
	Include: {},
	Trigger: {},
	Swap: {},
	Indicator: {},
	Vals: {},
	Confirm: {},
	PushURL: {},
	Boost: {},
	Constraint: {},
	DirtyWatch: {},
	DirtyGroup: {},
	EnableOnValid: {},
	EnableTarget: {},
	ConstraintForm: {},
	Checked: {},
	Required: {},
}})
  ]], {
    i(1, ""),
    i(2, ""),
    i(3, "Click Me"),
    i(4, "false"),
    i(5, "structs.POST"),
    i(6, "/endpoint"),
    i(7, ""),
    i(8, ""),
    i(9, ""),
    i(10, "innerHTML"),
    i(11, ""),
    i(12, ""),
    i(13, ""),
    i(14, ""),
    i(15, "false"),
    i(16, ""),
    i(17, "false"),
    i(18, ""),
    i(19, "false"),
    i(20, ""),
    i(21, "false"),
    i(22, "false"),
    i(23, "false"),
  })),


  s("radiotertiary", fmt([[
@components.TertiaryRadio(&structs.Radio{{
	ID: {},
	Name: {},
	Value: {},
	Disabled: {},
	Method: {},
	URL: {},
	Target: {},
	Include: {},
	Trigger: {},
	Swap: {},
	Indicator: {},
	Vals: {},
	Confirm: {},
	PushURL: {},
	Boost: {},
	Constraint: {},
	DirtyWatch: {},
	DirtyGroup: {},
	EnableOnValid: {},
	EnableTarget: {},
	ConstraintForm: {},
	Checked: {},
	Required: {},
}})
  ]], {
    i(1, ""),
    i(2, ""),
    i(3, "Click Me"),
    i(4, "false"),
    i(5, "structs.POST"),
    i(6, "/endpoint"),
    i(7, ""),
    i(8, ""),
    i(9, ""),
    i(10, "innerHTML"),
    i(11, ""),
    i(12, ""),
    i(13, ""),
    i(14, ""),
    i(15, "false"),
    i(16, ""),
    i(17, "false"),
    i(18, ""),
    i(19, "false"),
    i(20, ""),
    i(21, "false"),
    i(22, "false"),
    i(23, "false"),
  })),


  s("radioaccent", fmt([[
@components.AccentRadio(&structs.Radio{{
	ID: {},
	Name: {},
	Value: {},
	Disabled: {},
	Method: {},
	URL: {},
	Target: {},
	Include: {},
	Trigger: {},
	Swap: {},
	Indicator: {},
	Vals: {},
	Confirm: {},
	PushURL: {},
	Boost: {},
	Constraint: {},
	DirtyWatch: {},
	DirtyGroup: {},
	EnableOnValid: {},
	EnableTarget: {},
	ConstraintForm: {},
	Checked: {},
	Required: {},
}})
  ]], {
    i(1, ""),
    i(2, ""),
    i(3, "Click Me"),
    i(4, "false"),
    i(5, "structs.POST"),
    i(6, "/endpoint"),
    i(7, ""),
    i(8, ""),
    i(9, ""),
    i(10, "innerHTML"),
    i(11, ""),
    i(12, ""),
    i(13, ""),
    i(14, ""),
    i(15, "false"),
    i(16, ""),
    i(17, "false"),
    i(18, ""),
    i(19, "false"),
    i(20, ""),
    i(21, "false"),
    i(22, "false"),
    i(23, "false"),
  })),


  s("radiounique", fmt([[
@components.UniqueRadio(&structs.Radio{{
	ID: {},
	Name: {},
	Value: {},
	Disabled: {},
	Method: {},
	URL: {},
	Target: {},
	Include: {},
	Trigger: {},
	Swap: {},
	Indicator: {},
	Vals: {},
	Confirm: {},
	PushURL: {},
	Boost: {},
	Constraint: {},
	DirtyWatch: {},
	DirtyGroup: {},
	EnableOnValid: {},
	EnableTarget: {},
	ConstraintForm: {},
	Checked: {},
	Required: {},
}})
  ]], {
    i(1, ""),
    i(2, ""),
    i(3, "Click Me"),
    i(4, "false"),
    i(5, "structs.POST"),
    i(6, "/endpoint"),
    i(7, ""),
    i(8, ""),
    i(9, ""),
    i(10, "innerHTML"),
    i(11, ""),
    i(12, ""),
    i(13, ""),
    i(14, ""),
    i(15, "false"),
    i(16, ""),
    i(17, "false"),
    i(18, ""),
    i(19, "false"),
    i(20, ""),
    i(21, "false"),
    i(22, "false"),
    i(23, "false"),
  })),


  s("radioattention", fmt([[
@components.AttentionRadio(&structs.Radio{{
	ID: {},
	Name: {},
	Value: {},
	Disabled: {},
	Method: {},
	URL: {},
	Target: {},
	Include: {},
	Trigger: {},
	Swap: {},
	Indicator: {},
	Vals: {},
	Confirm: {},
	PushURL: {},
	Boost: {},
	Constraint: {},
	DirtyWatch: {},
	DirtyGroup: {},
	EnableOnValid: {},
	EnableTarget: {},
	ConstraintForm: {},
	Checked: {},
	Required: {},
}})
  ]], {
    i(1, ""),
    i(2, ""),
    i(3, "Click Me"),
    i(4, "false"),
    i(5, "structs.POST"),
    i(6, "/endpoint"),
    i(7, ""),
    i(8, ""),
    i(9, ""),
    i(10, "innerHTML"),
    i(11, ""),
    i(12, ""),
    i(13, ""),
    i(14, ""),
    i(15, "false"),
    i(16, ""),
    i(17, "false"),
    i(18, ""),
    i(19, "false"),
    i(20, ""),
    i(21, "false"),
    i(22, "false"),
    i(23, "false"),
  })),


}
